// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBOEEKlgJtKqhOxYX2Y7KhiaZg_GtN-JLI',
    appId: '1:676265042030:web:19af0b6aa281e856d7067f',
    messagingSenderId: '676265042030',
    projectId: 'sakhigbe-book-swap',
    authDomain: 'sakhigbe-book-swap.firebaseapp.com',
    storageBucket: 'sakhigbe-book-swap.firebasestorage.app',
    measurementId: 'G-TVF8WQHN9M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAICAP_hareWZUobXxFvi-iz46bAwQ19Sw',
    appId: '1:676265042030:android:c2ea638d8c5ee1d7d7067f',
    messagingSenderId: '676265042030',
    projectId: 'sakhigbe-book-swap',
    storageBucket: 'sakhigbe-book-swap.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC9oHDz6_6IhPpMsOqUiHDzXdAJeM_nrno',
    appId: '1:676265042030:ios:242403f8720491f9d7067f',
    messagingSenderId: '676265042030',
    projectId: 'sakhigbe-book-swap',
    storageBucket: 'sakhigbe-book-swap.firebasestorage.app',
    iosBundleId: 'com.example.bookSwap',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC9oHDz6_6IhPpMsOqUiHDzXdAJeM_nrno',
    appId: '1:676265042030:ios:242403f8720491f9d7067f',
    messagingSenderId: '676265042030',
    projectId: 'sakhigbe-book-swap',
    storageBucket: 'sakhigbe-book-swap.firebasestorage.app',
    iosBundleId: 'com.example.bookSwap',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBOEEKlgJtKqhOxYX2Y7KhiaZg_GtN-JLI',
    appId: '1:676265042030:web:fe377b16603377e7d7067f',
    messagingSenderId: '676265042030',
    projectId: 'sakhigbe-book-swap',
    authDomain: 'sakhigbe-book-swap.firebaseapp.com',
    storageBucket: 'sakhigbe-book-swap.firebasestorage.app',
    measurementId: 'G-7ZX03JQN32',
  );
}
